package ru.chaotika.app;

enum SttError {
    INVALID_SOURCE,
    LOCAL_STT_UNAVAILABLE,
    LOW_CONFIDENCE,
    NETWORK_ERROR,
    NO_SPEECH,
    PERMISSION_DENIED,
    PRIVACY_BLOCKED,
    RATE_LIMITED,
    REPLAY_REJECTED,
    SERVER_STT_UNAVAILABLE,
    TOO_LONG,
    TOO_QUIET,
    TOO_SHORT,
    UNSUPPORTED_AUDIO_FORMAT
}
