import {
  BellIcon,
  CalendarIcon,
  CalendarPageIcon,
  CarIcon,
  ChatIcon,
  CheckIcon,
  ChecklistIcon,
  ChildrenIcon,
  CleaningZonesIcon,
  CloseIcon,
  DogIcon,
  DownloadIcon,
  EditIcon,
  FolderIcon,
  GearIcon,
  HabitsTargetIcon,
  HeartIcon,
  HomeIcon,
  LightningIcon,
  MenuIcon,
  MinusIcon,
  MoreSlidersIcon,
  PlusIcon,
  SearchIcon,
  ShoppingCartIcon,
  SpheresChartIcon,
  TimelinePageIcon,
  TrashIcon,
  UploadIcon,
  UserIcon,
} from './Icon'

export const appIcons = {
  trash: TrashIcon,
  edit: EditIcon,
  close: CloseIcon,
  check: CheckIcon,
  'habits-target': HabitsTargetIcon,
  checklist: ChecklistIcon,
  dog: DogIcon,
  home: HomeIcon,
  'cleaning-zones': CleaningZonesIcon,
  children: ChildrenIcon,
  heart: HeartIcon,
  car: CarIcon,
  search: SearchIcon,
  settings: GearIcon,
  user: UserIcon,
  bell: BellIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  calendar: CalendarIcon,
  'calendar-page': CalendarPageIcon,
  'shopping-cart': ShoppingCartIcon,
  'spheres-chart': SpheresChartIcon,
  timeline: TimelinePageIcon,
  chat: ChatIcon,
  folder: FolderIcon,
  download: DownloadIcon,
  upload: UploadIcon,
  menu: MenuIcon,
  'more-sliders': MoreSlidersIcon,
  lightning: LightningIcon,
} as const
