import {
  BellIcon,
  CalendarIcon,
  CarIcon,
  ChatIcon,
  CheckIcon,
  ChildrenIcon,
  CloseIcon,
  DogIcon,
  DownloadIcon,
  EditIcon,
  FolderIcon,
  HeartIcon,
  HomeIcon,
  MenuIcon,
  MinusIcon,
  PlusIcon,
  SearchIcon,
  SettingsIcon,
  TrashIcon,
  UploadIcon,
  UserIcon,
} from './Icon'

export const appIcons = {
  trash: TrashIcon,
  edit: EditIcon,
  close: CloseIcon,
  check: CheckIcon,
  dog: DogIcon,
  home: HomeIcon,
  children: ChildrenIcon,
  heart: HeartIcon,
  car: CarIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  user: UserIcon,
  bell: BellIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  calendar: CalendarIcon,
  chat: ChatIcon,
  folder: FolderIcon,
  download: DownloadIcon,
  upload: UploadIcon,
  menu: MenuIcon,
} as const
