export {
  createSelfCareApiClient,
  type SelfCareApiClient,
  type SelfCareApiClientConfig,
  SelfCareApiError,
} from './lib/self-care-api'
export {
  getSelfCareErrorMessage,
  selfCareAnalyticsQueryKey,
  selfCareDashboardQueryKey,
  selfCareHistoryQueryKey,
  selfCareItemsQueryKey,
  selfCarePlanQueryKey,
  selfCareRitualStepDraftsQueryKey,
  selfCareSettingsQueryKey,
  selfCareTemplatesQueryKey,
  useArchiveSelfCareItem,
  useCancelSelfCareOccurrence,
  useCompleteSelfCareCourseSession,
  useCompleteSelfCareFlexibleGoal,
  useCompleteSelfCareItemNow,
  useCompleteSelfCareOccurrence,
  useCreateSelfCareItem,
  useCreateSelfCareItemFromTemplate,
  useDeleteSelfCareRitualStepDraft,
  useDisableSelfCareGentleMode,
  useEnableSelfCareGentleMode,
  useMoveSelfCareOccurrence,
  useScheduleSelfCareItem,
  useSelfCareAnalytics,
  useSelfCareDashboard,
  useSelfCareHistory,
  useSelfCareItems,
  useSelfCarePlan,
  useSelfCareRitualStepDrafts,
  useSelfCareSettings,
  useSelfCareTemplates,
  useSkipSelfCareOccurrence,
  useUpdateSelfCareItem,
  useUpdateSelfCareMinimumItems,
  useUpdateSelfCareSettings,
  useUpsertSelfCareDailyState,
  useUpsertSelfCareRitualStepDraft,
} from './lib/useSelfCare'
